"""create wallet table

Revision ID: 77b90025976c
Revises: 
Create Date: 2024-12-14 19:42:06.306268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b90025976c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallet',
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('customer_xid', sa.String(length=36), nullable=False),
    sa.Column('balance', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ENABLE', 'DISABLE', name='walletstatustype'), nullable=False),
    sa.PrimaryKeyConstraint('wallet_id')
    )
    op.create_index(op.f('ix_wallet_customer_xid'), 'wallet', ['customer_xid'], unique=False)
    op.create_table('wallet_state',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('wallet_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('ENABLE', 'DISABLE', name='walletstatustype'), nullable=False),
    sa.Column('changed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.wallet_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_state_wallet_id'), 'wallet_state', ['wallet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_state_wallet_id'), table_name='wallet_state')
    op.drop_table('wallet_state')
    op.drop_index(op.f('ix_wallet_customer_xid'), table_name='wallet')
    op.drop_table('wallet')
    # ### end Alembic commands ###
